### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [Hackerthonweb3/business-card#80]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by ottodevs** [comment]
Hi, @codehangen thanks for your interest and sorry for the late reply!

The project is currently on hold while we agree on some organisational decisions, maybe we resume development soon, but I would like to invite you to the project discord so we can continue discussion there https://discord.gg/aB9mpV9t

**Comment by ghost** [comment]
Hi ottodevs.

> Hi, @codehangen thanks for your interest and sorry for the late reply!
> The project is currently on hold while we agree on some organisational decisions, maybe we resume development soon, but I would like to invite you to the project discord so we can continue discussion there https://discord.gg/aB9mpV9t

thank you for feedback here.
